### ISSUE TITLE
Need DirectX 12 Edition

### ISSUE THREAD

**Issue by Nirmal4G** [Microsoft/Windows-appsample-marble-maze#1]
For People who are new to DirectX Platform, this sample already provides DX11, DX3D11 experience but it would be most helpful it could include a DX12 optimised version of the Game, also showing like a separate window with DX11, DX12 comparison like in the BUILD-2015 DX12 Videos

Please consider this option. It would be really helpful for new people like myself.

**Comment by scottmill** [comment]
Thanks for the suggestion!  We currently don't have a DX12 port planned for Marble Maze, however we do have several DX12 samples available here: https://github.com/Microsoft/DirectX-Graphics-Samples

**Comment by Nirmal4G** [comment]
Will you be able to do this in the future or no plans for porting at all?

**Comment by scottmill** [comment]
It's a possibility in the future, but currently there are no plans for porting.

**Comment by Nirmal4G** [comment]
I saw those samples and then I asked here, because a real game implementing DX12 specific features and how the optimizations are done would be very helpful than the samples explaining those features.

Anyway thank you, looking forward to the possibility.
