### ISSUE TITLE
Uses Integrated instead of Discrete GPU

### ISSUE THREAD

**Issue by stonstad** [Microsoft/Windows-appsample-marble-maze#4]
... as a result, I am seeing subpar framerate.  How do we modify a DirectX C++ UWP app to use a discrete card when available?

**Comment by sjointer** [comment]
This isn't an "official" answer, but I was under the impression that there is a method in DirectX that you call which returns all the available graphics adapters, and another method that you call to determine the capabilities of each specific adapter, then choose the one you want to use.  I'm not certain what that method is exactly.  If I come across it, I will post again and update this answer.

**Comment by KarlErickson** [comment]
Sorry, I don't have an answer either. Your best chance, if you don't already have an answer, is to ask on one of the user forums out there, such as https://social.msdn.microsoft.com/Forums/windowsapps/en-US/home?forum=wpdevelop.
